In [1]:
a=10
b=20
print(a+b)

30


In [3]:
name=input("Enter the name:")
print(name)

Enter the name: Gomathiiiiiiiiiiiiiiiiiiii


Gomathiiiiiiiiiiiiiiiiiiii


In [8]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)
print("\nData Type:")
print(type(arr))
print("\nShape:")
print(arr.shape)
print("\nDimensions:")
print(arr.ndim)
print("\nSize:")
print(arr.size)
print("\nAddition (+10):")
print(arr + 10)
print("\nMultiplication (*2):")
print(arr * 2)
print("\nDivision (/2):")
print(arr / 2)
print("\nZeros Array:")
print(np.zeros(5))
print("\nOnes Array:")
print(np.ones(5))
print("\nRange Array (1 to 10):")
print(np.arange(1, 11))
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n2D Array:")
print(arr2)
print("\n2D Array Shape:")
print(arr2.shape)
print("\n2D Array Dimensions:")
print(arr2.ndim)

Array:
[10 20 30 40 50]

Data Type:
<class 'numpy.ndarray'>

Shape:
(5,)

Dimensions:
1

Size:
5

Addition (+10):
[20 30 40 50 60]

Multiplication (*2):
[ 20  40  60  80 100]

Division (/2):
[ 5. 10. 15. 20. 25.]

Zeros Array:
[0. 0. 0. 0. 0.]

Ones Array:
[1. 1. 1. 1. 1.]

Range Array (1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[1 2 3]
 [4 5 6]]

2D Array Shape:
(2, 3)

2D Array Dimensions:
2
